baseURL = 'https://agri-tech-solutions.github.io/kilimo-website/'
languageCode = 'en-us'
title = 'Kilimo'
disableKinds = ['taxonomy', 'term']
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
